# -*- coding: utf-8 -*-
"""Simple Project 1: Students Performance Analyzer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1te-XhlbypEmjwQ4f2QSpAqhqgvpNtx2M

Based from the Kaggle dataset: Students Performance in Exams (Fictional/Practice Data)

Link: https://www.kaggle.com/datasets/spscientist/students-performance-in-exams/data
"""

#Importing the dataset
import pandas as pd
import sqlite3
import kagglehub

df = pd.read_csv('StudentsPerformance.csv')

print(df.shape)
df.head()

#Summary of the dataset
conn = sqlite3.connect('students.db')
df.to_sql('students', conn, if_exists='replace', index=False)

result = pd.read_sql_query('SELECT * FROM students', conn)
print(result.describe())

#For checking if there were errors or missing data in the table
import duckdb

sql_df = duckdb.query("""
    SELECT * FROM result
""").df()

print(sql_df.isnull().sum())
print('')
print(sql_df.duplicated().sum())
print('')
print(sql_df.dtypes)
print('')
print(sql_df['gender'].unique())
print(sql_df['parental level of education'].unique())
print(sql_df['test preparation course'].unique())

"""Focusing on the averages of each potential category"""

import duckdb
import seaborn as sns
import matplotlib.pyplot as plt

sql_df = duckdb.query("""
    SELECT "gender",
      AVG("math score") AS "Average Math Score",
      AVG("reading score") AS "Average Reading Score",
      AVG("writing score") AS "Average Writing Score"
    FROM df
    GROUP BY "gender"
""").df()

import duckdb

sql_df = duckdb.query("""
    SELECT "parental level of education",
      AVG("math score") AS "Average Math Score",
      AVG("reading score") AS "Average Reading Score",
      AVG("writing score") AS "Average Writing Score"
    FROM df
    GROUP BY "parental level of education"
""").df()

import duckdb

sql_df = duckdb.query("""
    SELECT "test preparation course",
      AVG("math score") AS "Average Math Score",
      AVG("reading score") AS "Average Reading Score",
      AVG("writing score") AS "Average Writing Score"
    FROM df
    GROUP BY "test preparation course"
""").df()

sql_df

"""Visualization of the averages score of students per category (in score form)"""

import seaborn as sns
import matplotlib.pyplot as plt

ax = sns.histplot(data=df, x='math score', hue='gender', multiple='layer', kde=True)
ax.set_title('Gender vs Math score')
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

ax = sns.histplot(data=df, x='reading score', hue='gender', multiple='layer', kde=True)
ax.set_title('Gender vs Math score')
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

ax = sns.histplot(data=df, x='math score', hue='test preparation course', multiple='layer', kde=True)
ax.set_title('Subject Scores')
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

ax = sns.histplot(data=df, x='reading score', hue='test preparation course', multiple='layer', kde=True)
ax.set_title('Subject Scores')
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

ax = sns.histplot(data=df, x='writing score', hue='test preparation course', multiple='layer', kde=True)
ax.set_title('Subject Scores')
plt.show()

#Using .corr() to find the corelation of the math score, reading score, and writing score
mat = df.corr(numeric_only=True)
print(mat)

#Using sklearn to find the linear regression for close checking and finalization of the code
from sklearn.linear_model import LinearRegression

x = df[['math score']]
y = df[['writing score']]

model = LinearRegression()
model.fit(x, y)
predictions = model.predict(x)

print(model.score(x, y)) # R² value — how much variance is explained
print(model.coef_)
print(model.intercept_)

from sklearn.linear_model import LinearRegression

x = df[['math score']]
y = df[['reading score']]

model = LinearRegression()
model.fit(x, y)
predictions = model.predict(x)

print(model.score(x, y)) # R² value — how much variance is explained
print(model.coef_)
print(model.intercept_)

from sklearn.linear_model import LinearRegression

x = df[['reading score']]
y = df[['writing score']]

model = LinearRegression()
model.fit(x, y)
predictions = model.predict(x)

print(model.score(x, y)) # R² value — how much variance is explained
print(model.coef_)
print(model.intercept_)

"""Analysis based on the Observations and Results:

In the dataset, comparing subject scores based in test preparation course seems easier than other categories because it has similar pattern where the student's average who completed it has a higher average score than the ones who did not. However, there are noticable factors on the average scores with the gender, where female students have higher reading scores than males, but male students have higher math scores than females. Now, to futher support my analysis in test prep course, the means of students who have completed test prep courses have higher scores than the ones who did not even though there are more students who ended up in the average graph (completed: 69.7[math], 73.9[reading], 74.4[writing] vs none: 64.1[math], 66.5[reading],	64.5[writing]). Lastly, is the correlationship and linear regression, as you notice the correlationship, reading and writing is more correlated with 0.95 being the closest to one; however it does not mean that they cause they score changes. While math, is the outlier as it is the furthest score between all of them three.
"""